In [7]:
from google.colab import auth
auth.authenticate_user()

from google.cloud import bigquery

client = bigquery.Client('scaler-sql-476312')

# **JOINS**

In [8]:
# How do we know the primary key basically it will mention in ER Diagram if they didn't there is a way we can find the primary key
query = """
SELECT count(*) as no_of_rows , count(customer_id) as unique
FROM `farmers_market.customer_purchases`
"""
df = client.query(query).to_dataframe()
df

# Since they both are same so customer_id is a Primary key for customer table

   no_of_rows  unique
0        1003    1003

In [9]:
 # Question - – Get a list of customers' zip codes for customers who made a purchase on 2019-04-06.
query = """
SELECT cu.customer_zip
FROM `farmers_market.customer` cu
LEFT JOIN `farmers_market.customer_purchases` cp
  ON cu.customer_id = cp.customer_id
WHERE cp.market_date = "2019-04-06"
"""

df = client.query(query).to_dataframe()
df

   customer_zip
0         22801
1         22801
2         22801
3         22801
4         22801
5         22821
6         22821
7         22821

In [10]:
 # Question - – Get the list of customers who have never made any purchase
query = """
SELECT cu.customer_id,cu.customer_first_name
FROM `farmers_market.customer` cu
LEFT JOIN `farmers_market.customer_purchases` cp
  USING (customer_id)
WHERE cp.customer_id IS NULL
"""

df = client.query(query).to_dataframe()
df

   customer_id customer_first_name
0           56               Rohit
1           55               James